### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [Meebuhs/newtab#1]
Hi...
I'm Chimzy, I came across your amazing project and I really liked it.
As a logo designer who loves to contribute to amazing open source projects, I want to help create a New Logo/Icon for your project that will represent your project and give it a unique identity.

Working on an idea concept at the moment, I will share it here once i am done, so you can give me your feedback on any adjustments or changes you might want.

I will really appreciate your response...

Regards!

**Comment by Meebuhs** [comment]
Hi Chimzy,

That sounds great, I appreciate that you've taken an interest in this project. 
It's a fair way away from a release and development has been light the past few months. I'll likely pick it up again in a couple weeks when my uni semester finishes.

There isn't much in the way of requirements as the project is still in its early stages. It would only be important that the icon is useable and recognisable at 16x16, for the favicon and browser action icon.

Looking forward to seeing what you come up with!

**Comment by chimzycash** [comment]
I really appreciate your feedback... Would get the idea concept ready for your feedback

**Comment by chimzycash** [comment]
Hello @Meebuhs ... Here is my idea concept design of the logo... You can give your feedback and also suggest your preferred logo color of choice.

![LOGO DESIGN_Newtab_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/59149237-01253600-8a0b-11e9-899b-25d48c770058.jpg)
![LOGO DESIGN_Newtab_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/59149238-01bdcc80-8a0b-11e9-9b06-6ad7bbc5d504.jpg)
![LOGO DESIGN_Newtab_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/59149239-01bdcc80-8a0b-11e9-8674-e5a0e41ca822.jpg)
![LOGO DESIGN_Newtab_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/59149240-02566300-8a0b-11e9-88e0-aed5263a2688.jpg)
![LOGO DESIGN_Newtab_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/59149241-02eef980-8a0b-11e9-85a6-9e18b6507961.jpg)
![LOGO DESIGN_Newtab_idea concept_NEW](https://user-images.githubusercontent.com/37814297/59149393-b3a9c880-8a0c-11e9-91e8-af51d0b867bc.jpg)

**Comment by Meebuhs** [comment]
Hi @chimzycash these are great! 

I'm really impressed with how these turned out and how quickly you were able to produce them.

The colour looks good to me, I'll be sure to integrate it into the design throughout as development continues.
As far as feedback goes,  would it be posisble to swap the bold sections? So that the emphasis is on 'new' rather than 'tab'

**Comment by chimzycash** [comment]
I really appreciate your response, and glad that you liked the design...
Would make the adjustment on the text

**Comment by chimzycash** [comment]
Hi... Here is the adjustment

![LOGO DESIGN_Newtab_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/59501379-504bea80-8e93-11e9-9249-5ed541f59b02.jpg)
![LOGO DESIGN_Newtab_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/59501382-50e48100-8e93-11e9-82e9-e9f6da99d2f1.jpg)
![LOGO DESIGN_Newtab_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/59501383-517d1780-8e93-11e9-8cf9-357fb750c717.jpg)

**Comment by Meebuhs** [comment]
This is great chimzy, thanks!

**Comment by chimzycash** [comment]
I appreciate.. Glad that you liked it... 
Would prepare all the files for your use

**Comment by chimzycash** [comment]
Here is the Google Drive link to the logo files including the vector files

https://drive.google.com/drive/folders/1-VBJj4Msy0Vf_EeB39kP0uYGqtel4UyU?usp=sharing
